### ISSUE TITLE
how do we protect money dollar sign from math protection

### ISSUE THREAD

**Issue by maelle** [ropensci/tinkr#121]
:wave: @zkamvar I am realizing I do not know how to fix the problem below without resorting to backticks:

``` r
lines <- "With this $340k granta,"
file <- withr::local_tempfile()
brio::write_lines(lines, file)

tinkr::yarn$new(file)$protect_math()
#> Error: Inline math delimiters are not balanced.
#> 
#> HINT: If you are writing BASIC code, make sure you wrap variable
#>       names and code in backtics like so: `INKEY$`.
#> 
#> Below are the pairs that were found:
#>                   start...end
#>                   -----...---
#> With this $340k granta,...
```

<sup>Created on 2024-10-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Any hint?

**Comment by zkamvar** [comment]
oof that's not great and is definitely a bug.

**Comment by zkamvar** [comment]
Ugh.... I realize now that all of the examples we have are balanced -_-. I'm not sure why I never noticed this before: 

https://github.com/ropensci/tinkr/blob/8a57235f7072dbcb7eb22516290c58b692a9c015/inst/extdata/basic-math.md?plain=1#L7-L14

**Comment by zkamvar** [comment]
I think the solution may be in here:

https://github.com/ropensci/tinkr/blob/8a57235f7072dbcb7eb22516290c58b692a9c015/R/asis-nodes.R#L143-L149

If we check that `lh` is zero, then we can exit early.

**Comment by zkamvar** [comment]
As noted in https://github.com/ropensci/tinkr/pull/122#issue-2580161441, this will still be a problem if there is broken math that needs fixing:

```markdown
This is an example with a bunch of broken math.

## Broken math mixed with currency. 

I bet you $5 that 

$P \ne
NP$

$P 
\eq NP$

I bet you $10 that... no,
I bet you $20 that 

$P \gt
NP$

$P 
\lt NP$

Give me $5.

## broken math on the same line

$P \eq
NP$ and $P \ne
NP$
```

We use regex to detect the broken math and isolate the text nodes that contain the broken math. Since broken math is generally on adjacent lines, we assume that these nodes are next to each other where the odd nodes are the opening sign and the even nodes are the corresponding closing signs. 

Currency dollars throw this off because they create an offset in the opening signs and need to be addressed, but I get a feeling it will need to be a sort of recursive function that walks down the nodes, checks for pairs, discarding unpaired dollars along the way so that the zipper works.
